//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoAdmin.Model
{
    using System;
    using System.Collections.Generic;
    
    using ArduinoAdmin.Lib;
    using System.Windows;
    public partial class Etat : ModelBase
    {
    
    	// Constructeur par copie
        public Etat(Etat e)
        {
    		if(e == null)
    			return;
    		// Clone les membres
    		Copy(this, e);
        }
    	
    	// Constructeur
        public Etat()
        {
        }
    	
    	// Copie une instance dans une autre
        public static Etat Copy(Etat dst, Etat src)
        {
    		// Assigne les membres
            dst.Etat_Id = src.Etat_Id;
            dst.Equipement_Id = src.Equipement_Id;
            dst.Nom = src.Nom;
            dst.Valeur = src.Valeur;
    
            dst.Equipement = src.Equipement;
    
    		return dst;
        }
    	
    	// Copie une instance dans une autre
        public static int Compare(Etat dst, Etat src)
        {
    		int i=0;
    		// Assigne les membres
             if(dst.Etat_Id != src.Etat_Id)
    			i++;
             if(dst.Equipement_Id != src.Equipement_Id)
    			i++;
             if(dst.Nom != src.Nom)
    			i++;
             if(dst.Valeur != src.Valeur)
    			i++;
    
             if(dst.Equipement != src.Equipement)
    			i++;
    
    		return i;
        }
    	
    	// Vérifie si l'entité existe en BDD (Application dependant)
        public bool IsPersistant
        {
            get
            {
                return (((App)Application.Current).bdd.Entry(this).State == System.Data.Entity.EntityState.Detached)  ? false : true;
            }
        }
    
    	// Copie l'instance dans le presse-papier
        public void ToClipboard()
        {
            //Ecrit au format Texte (préférer une serialization XML)
            // !!Attention!! Pas de gestion des valeurs 'null'; Pas de gestion des string avec '\0'
    		string txt = "";
    
    		// Assigne les membres
    		txt += "Etat_Id:" + Etat_Id.ToString() + "\0";
    		txt += "Equipement_Id:" + (Equipement_Id==null ? "" : Equipement_Id.ToString()) + "\0";
    		txt += "Nom:" + Nom.ToString() + "\0";
    		txt += "Valeur:" + Valeur.ToString() + "\0";
    
    		Console.WriteLine("ToClipboard="+txt.Replace('\0','#'));
    		Clipboard.SetData("text/Etat", txt);
        }
    	
    	// Charge l'instance depuis le presse-papier
        public void FromClipboard()
        {
            //Lit au format Texte (préférer une serialization XML)
            // !!Attention!! Pas de gestion des valeurs 'null'; Pas de gestion des string avec '\0'
            if (Clipboard.ContainsData("text/Etat"))
            {
    
    			string txt = Clipboard.GetData("text/Etat") as string;
    			string[] elements = txt.Split('\0');
    
    			foreach (string s in elements)
    			{
    				// recupere le nom et la valeur de la propriété
    				int separatorIndex = s.IndexOf(':');
    				if (separatorIndex < 1)
    					continue;
    				string property_name = s.Substring(0, separatorIndex);
    				string property_value = s.Substring(separatorIndex+1);
    			
    				// charge les paramètres
    				switch(property_name){
    					case "Etat_Id":
    						try
    						{
    							//False
    							this.Etat_Id = int.Parse(property_value);
    						}
    						catch
    						{
    							this.Etat_Id = new int();
    						}
    						break;
    					case "Equipement_Id":
    						try
    						{
    							//True
    							this.Equipement_Id = int.Parse(property_value);
    						}
    						catch
    						{
    							this.Equipement_Id = null;
    						}
    						break;
    					case "Nom":
    						this.Nom = property_value;
    						break;
    					case "Valeur":
    						this.Valeur = property_value;
    						break;
    				}
    				Console.WriteLine(property_name + "=" + property_value + "("+ this.GetType().GetProperty(property_name).GetValue(this) + ")");
    			}
    		}
        }
    	
    	// Vérifie si le presse-papier contient une instance de ce type
        public static bool HasClipboard()
        {
            return Clipboard.ContainsData("text/Etat");
        }
    	
    
    	// Propriétés de données
    	private int _etat_id;
    	public int Etat_Id { get { return _etat_id; } set { _etat_id = value; OnPropertyChanged("Etat_Id");} }
    	private Nullable<int> _equipement_id;
    	public Nullable<int> Equipement_Id { get { return _equipement_id; } set { _equipement_id = value; OnPropertyChanged("Equipement_Id");} }
    	private string _nom;
    	public string Nom { get { return _nom; } set { _nom = value; OnPropertyChanged("Nom");} }
    	private string _valeur;
    	public string Valeur { get { return _valeur; } set { _valeur = value; OnPropertyChanged("Valeur");} }
    	// Propriétés de navigation
    	private Equipement _equipement;
        public virtual Equipement Equipement { get { return _equipement; } set { _equipement = value; OnPropertyChanged("Equipement");} }
    }
}
