//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoAdmin.Model
{
    using System;
    using System.Collections.Generic;
    
    using ArduinoAdmin.Lib;
    using System.Windows;
    public partial class Serveur : ModelBase
    {
    
    	// Constructeur par copie
        public Serveur(Serveur e)
        {
    		if(e == null)
    			return;
    		// Clone les membres
    		Copy(this, e);
        }
    	
    	// Constructeur
        public Serveur()
        {
            this.Equipement = new HashSet<Equipement>();
        }
    	
    	// Copie une instance dans une autre
        public static Serveur Copy(Serveur dst, Serveur src)
        {
    		// Assigne les membres
            dst.Serveur_Id = src.Serveur_Id;
            dst.AdressePhysique = src.AdressePhysique;
            dst.Jeton = src.Jeton;
            dst.AdresseIP = src.AdresseIP;
    
            dst.Equipement = src.Equipement;
    
    		return dst;
        }
    	
    	// Copie une instance dans une autre
        public static int Compare(Serveur dst, Serveur src)
        {
    		int i=0;
    		// Assigne les membres
             if(dst.Serveur_Id != src.Serveur_Id)
    			i++;
             if(dst.AdressePhysique != src.AdressePhysique)
    			i++;
             if(dst.Jeton != src.Jeton)
    			i++;
             if(dst.AdresseIP != src.AdresseIP)
    			i++;
    
             if(dst.Equipement != src.Equipement)
    			i++;
    
    		return i;
        }
    	
    	// Vérifie si l'entité existe en BDD (Application dependant)
        public bool IsPersistant
        {
            get
            {
                return (((App)Application.Current).bdd.Entry(this).State == System.Data.Entity.EntityState.Detached)  ? false : true;
            }
        }
    
    	// Copie l'instance dans le presse-papier
        public void ToClipboard()
        {
            //Ecrit au format Texte (préférer une serialization XML)
            // !!Attention!! Pas de gestion des valeurs 'null'; Pas de gestion des string avec '\0'
    		string txt = "";
    
    		// Assigne les membres
    		txt += "Serveur_Id:" + Serveur_Id.ToString() + "\0";
    		txt += "AdressePhysique:" + AdressePhysique.ToString() + "\0";
    		txt += "Jeton:" + Jeton.ToString() + "\0";
    		txt += "AdresseIP:" + AdresseIP.ToString() + "\0";
    
    		Console.WriteLine("ToClipboard="+txt.Replace('\0','#'));
    		Clipboard.SetData("text/Serveur", txt);
        }
    	
    	// Charge l'instance depuis le presse-papier
        public void FromClipboard()
        {
            //Lit au format Texte (préférer une serialization XML)
            // !!Attention!! Pas de gestion des valeurs 'null'; Pas de gestion des string avec '\0'
            if (Clipboard.ContainsData("text/Serveur"))
            {
    
    			string txt = Clipboard.GetData("text/Serveur") as string;
    			string[] elements = txt.Split('\0');
    
    			foreach (string s in elements)
    			{
    				// recupere le nom et la valeur de la propriété
    				int separatorIndex = s.IndexOf(':');
    				if (separatorIndex < 1)
    					continue;
    				string property_name = s.Substring(0, separatorIndex);
    				string property_value = s.Substring(separatorIndex+1);
    			
    				// charge les paramètres
    				switch(property_name){
    					case "Serveur_Id":
    						try
    						{
    							//False
    							this.Serveur_Id = int.Parse(property_value);
    						}
    						catch
    						{
    							this.Serveur_Id = new int();
    						}
    						break;
    					case "AdressePhysique":
    						this.AdressePhysique = property_value;
    						break;
    					case "Jeton":
    						this.Jeton = property_value;
    						break;
    					case "AdresseIP":
    						this.AdresseIP = property_value;
    						break;
    				}
    				Console.WriteLine(property_name + "=" + property_value + "("+ this.GetType().GetProperty(property_name).GetValue(this) + ")");
    			}
    		}
        }
    	
    	// Vérifie si le presse-papier contient une instance de ce type
        public static bool HasClipboard()
        {
            return Clipboard.ContainsData("text/Serveur");
        }
    	
    
    	
    	// Propriétés de données
    	private int _serveur_id;
    	public int Serveur_Id { get { return _serveur_id; } set { _serveur_id = value; OnPropertyChanged("Serveur_Id");} }
    	private string _adressephysique;
    	public string AdressePhysique { get { return _adressephysique; } set { _adressephysique = value; OnPropertyChanged("AdressePhysique");} }
    	private string _jeton;
    	public string Jeton { get { return _jeton; } set { _jeton = value; OnPropertyChanged("Jeton");} }
    	private string _adresseip;
    	public string AdresseIP { get { return _adresseip; } set { _adresseip = value; OnPropertyChanged("AdresseIP");} }
    	// Propriétés de navigation
    	private ICollection<Equipement> _equipement;
        public virtual ICollection<Equipement> Equipement { get { return _equipement; } set { _equipement = value; OnPropertyChanged("Equipement");} }
    }
}
